### ISSUE TITLE
How to install catpicture on Linux?

### ISSUE THREAD

**Issue by danijar** [JosephCatrambone/catpicture#1]

**Comment by JosephCatrambone** [comment]
Rust is required to build catpicture on Linux.  Alternatively, download a pre-build binary here: http://www.josephcatrambone.com/projects/catpicture/catpicture_linux (64-bit) and put it somewhere on your system path.  (/usr/share/bin/catpicture for example).

If you want to build it, you need to have Rust 1.9 or greater installed.

```
git clone https://github.com/josephcatrambone/catpicture
cd catpicture
cargo build --release
```

Copy build from the build directory (./target/release/catpicture) into a directory in your path.  If you see issues about Rayon, that's a library discrepancy.  I don't have a solution for it yet.
